### ISSUE TITLE
insights registeration

### ISSUE THREAD

**Issue by gburges** [redhataccess/insights-client#46] opened 2016-01-18 12:24 UTC
Hello,

After unregistering a system, i cannot reregister. Nor even the force-reregister works. We're getting:

```
redhat-access-insights --register
This machine has been unregistered
Use --register if you would like to re-register this machine
Exiting
```

**Comment by gravitypriest** [comment] 2016-01-18 14:22
Hi there gburges,

Could you tell me what version you are running with redhat-access-insights --version?

**Comment by a13m** [comment] 2016-01-19 13:57
@jcrafts I worked through this with @gburges ; the issue is that if you have a system with a duplicate ID (e.g., because it's been cloned from another system), doing an "unregister" isn't the right operation.  You have to manually remove the machine-id and .registered files and then register.  If you do "unregister", then you have to manually remove the machine-id and .unregistered files (and probably also go re-register the original machine with the same machine-id).  It would be nice if "force-register" would just reset the state, removing any necessary files, and do a new registration.

Current version is redhat-access-insights-1.0.5-0.el6_7.noarch

**Comment by gravitypriest** [comment] 2016-01-19 14:25
Thanks for the info!  Just for completeness sake, is there any chance you could post the contents of the log file?

**Comment by lphiri** [comment] 2016-01-19 14:27
+1  To updating "force-register"  to clean up machine-id and other registration files.

**Comment by gravitypriest** [comment] 2016-01-19 15:21
The unregister -> register flow is broken in version 1.0.5.  I recommend you update to 1.0.7 -- you can find the builds here: https://copr.fedoraproject.org/coprs/dvarga/insights-client/build/151823/

Updating --force-reregister to do this behavior still sounds like a good idea to me, though.

**Comment by gravitypriest** [comment] 2016-01-20 02:10
Closing this since it was fixed some time ago -- it is a bug present in an earlier version.  Will reopen if needed.

**Closed as completed by gravitypriest** 2016-01-20 02:10 UTC
